Extra Variables added for INCORE specific
ncsa/datawolf pull request #36
Opened 2024-10-17 20:08 UTC by ywkim312

2024-10-17 22:23 UTC, ywkim312 commented on charts/datawolf/templates/deployment.yaml
> +            - name: DATASET_DAO
> {{ if .Values.extraEnvVars -}}
>     {{ .Values.extraEnvVars | toYaml | nindent 12 }}
>     {{ end -}}

does above work? It didn't create -name, value pair so I made it like
            {{- if .Values.extraEnvVars }}
            {{- range $key, $value := .Values.extraEnvVars }}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            
so we can just simply put like

extraEnvVars:
  INCORE_USER: incore_user
  
  in values.yaml

2024-10-17 22:23 UTC, ywkim312 commented on charts/datawolf/values.yaml
> +extraEnvVars:
updated

2024-10-17 22:24 UTC, ywkim312 commented on charts/datawolf/templates/deployment.yaml
> +            - name: DATASET_DAO
> next in the in-core helm chart we can add to the datawolf section the variables.

I will work on it

2024-10-17 22:32 UTC, ywkim312 commented on charts/datawolf/templates/deployment.yaml
> +            - name: DATASET_DAO
> {{ if .Values.extraEnvVars -}}
>     {{ .Values.extraEnvVars | toYaml | nindent 12 }}
>     {{ end -}}

Never mind, I changed it your way. I will make the incore helm to work with this.

2024-10-23 16:05 UTC, robkooper commented on CHANGELOG.md
> +- Extra environment variables for IN-CORE specific [#35](https://github.com/ncsa/datawolf/issues/35)
```suggestion
- Ability for extra environment variables (used by IN-CORE) [#35](https://github.com/ncsa/datawolf/issues/35)
```

2024-10-23 16:06 UTC, robkooper requested changes
small tweak of changelog

2024-10-23 16:10 UTC, ywkim312 commented on CHANGELOG.md
> +- Extra environment variables for IN-CORE specific [#35](https://github.com/ncsa/datawolf/issues/35)
Updated as suggested

2024-10-23 16:10 UTC, ywkim312 commented
> small tweak of changelog

implemented

2024-10-23 16:19 UTC, robkooper approved these changes

2024-10-24 18:21 UTC, navarroc approved these changes

2024-10-24 18:23 UTC, merged