Release 4.6.1
ncsa/datawolf pull request #38
Opened 2024-10-29 21:10 UTC by ywkim312

2024-10-30 02:05 UTC, robkooper requested changes

2024-10-30 02:05 UTC, robkooper commented on CHANGELOG.md
looking at all the changes i think this is 4.7.0 and not just some changes to the helm chart.
make sure to remove the SNAPSHOT from all the poms

2024-10-30 13:53 UTC, ywkim312 commented on CHANGELOG.md
Changed to release 4.7.0. Also updated pom.xml files by removing the SNAPSHOT. Why this happens? Is this automatic update? Also, I see some other version like 3.1.0-SNAPSHOT in other datawolf components, such as datawolf-excutor-commandline-ui or others. Should this also be updated to 4.7.0?

2024-10-30 17:39 UTC, navarroc commented on CHANGELOG.md
With a maven build, you can create as many SNAPSHOT builds as you want; however, you can only push a single release so when we do a release, we remove SNAPSHOT and when we merge to main, this will push a release version (4.7.0). 

You can ignore the 3.1.0-SNAPSHOT. They are no longer used or haven't been used in a long time and aren't part of the standard build.

2024-10-30 17:40 UTC, ywkim312 commented on CHANGELOG.md
I see. Thanks for the explanation. If things look good. Let's get it merged and released so we can test datawolf in incore tst cluseter

2024-10-30 17:53 UTC, navarroc approved these changes
From what I can see, everything looks good. I didn't find any pom.xml files that need updating and CHANGELOG sets the release date/version.

2024-10-31 02:53 UTC, robkooper approved these changes
LGTM

2024-10-31 14:05 UTC, merged